apiVersion: batch/v1
kind: Job
metadata:
  name: coalesce-printer
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: printer
        image: alpine
        command: ["sh", "-c", "for n in $(seq 1 120); do echo $n; sleep 1; done"]
